name: actionlint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: actionlint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Workflow YAML lint
    permissions:
      contents: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/actionlint.yml@1acba687361415b3f5942acceb40b228bb0387fd # 0.2.4
