name: dependency-review

on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: dependency-review-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    name: dependency-review
    permissions:
      contents: read
      pull-requests: write
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-dependency-review.yml@1acba687361415b3f5942acceb40b228bb0387fd # 0.2.4
    with:
      fail_on_severity: high
      vulnerability_check: true
