name: dependency-review

on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: dependency-review-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    name: dependency-review
    permissions:
      contents: read
      pull-requests: write
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-dependency-review.yml@86f3e6d70a632561527379e5f962f57de81eb751 # 0.2.4
    with:
      fail_on_severity: high
      vulnerability_check: true
